version: "3"
services:
  nginx-proxy:
    image: "jwilder/nginx-proxy"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      #- ./nginx-proxy:/etc/nginx/conf.d/
    ports:
      - "80:80"
    networks:
      - front
  de:
    image: "sparkpos/docker-nginx-php"
    volumes:
      - ~/your-code:/var/www/html 
      - ./php-fpm/fpm-pool.conf:/etc/php/7.1/fpm/pool.d/www.conf
    environment:
      - VIRTUAL_HOST=de.dev
    networks:
      - front

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.254.0/24
